

class FinalizedException(Exception):
    def __init__(self):
        pass

